//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassIssueSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Company
    {
        public Company()
        {
            this.PassRequestHeds = new HashSet<PassRequestHed>();
        }
    
        [Key]
        public string CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string BOIApproveNo { get; set; }
        public System.DateTime BOIApproveDate { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Fax { get; set; }
        public decimal Status { get; set; }
        public System.DateTime AddDate { get; set; }
        public string AddUser { get; set; }
    
        public virtual ICollection<PassRequestHed> PassRequestHeds { get; set; }
    }
}
