//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassIssueSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<CardDetail> CardDetails { get; set; }
        public DbSet<CheckInPerson> CheckInPersons { get; set; }
        public DbSet<CheckInVehicle> CheckInVehicles { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<CompanyLogin> CompanyLogins { get; set; }
        public DbSet<GenerateRefNo> GenerateRefNoes { get; set; }
        public DbSet<PassIssueDet> PassIssueDets { get; set; }
        public DbSet<PassIssueHed> PassIssueHeds { get; set; }
        public DbSet<PassIssueVehicle> PassIssueVehicles { get; set; }
        public DbSet<PassRequestDet> PassRequestDets { get; set; }
        public DbSet<PassRequestHed> PassRequestHeds { get; set; }
        public DbSet<PassReqVehicle> PassReqVehicles { get; set; }
        public DbSet<PassType> PassTypes { get; set; }
        public DbSet<PaymentDetail> PaymentDetails { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<VehicleType> VehicleTypes { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
