//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassIssueSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenerateRefNo
    {
        public string TRName { get; set; }
        public string TRPrefix { get; set; }
        public decimal TRVal { get; set; }
    }
}
