//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassIssueSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PassIssueDet
    {
        [Key]
        public string PassNo { get; set; }
        public string PersonNIC { get; set; }
        public string MobileNo { get; set; }
    
        public virtual CheckInPerson CheckInPerson { get; set; }
        public virtual PassIssueDet PassIssueDet1 { get; set; }
        public virtual PassIssueDet PassIssueDet2 { get; set; }
    }
}
