//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassIssueSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PassRequestHed
    {
        public PassRequestHed()
        {
            this.PassRequestDets = new HashSet<PassRequestDet>();
            this.PassReqVehicles = new HashSet<PassReqVehicle>();
            this.PassIssueHeds = new HashSet<PassIssueHed>();
        }

        [Key]
        [Display(Name = "Pass Request No")]
        public string PassReqNo { get; set; }

        [Required]
        [Display(Name = "Company ID")]
        public string CompanyID { get; set; }

        [Required]
        [Display(Name = "Required From")]
        public System.DateTime RequiredFrom { get; set; }

        [Required]
        [Display(Name = "Required To")]
        public System.DateTime RequiredTo { get; set; }

        [Display(Name = "Comments")]
        public string Comments { get; set; }

        public System.DateTime AddDate { get; set; }
        public string AddUser { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<PassRequestDet> PassRequestDets { get; set; }
        public virtual ICollection<PassReqVehicle> PassReqVehicles { get; set; }
        public virtual ICollection<PassIssueHed> PassIssueHeds { get; set; }
    }
}
