//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassIssueSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PassIssueVehicle
    {
        [Key]
        public string PassNo { get; set; }
        public string VehicleNo { get; set; }
    
        public virtual CheckInVehicle CheckInVehicle { get; set; }
    }
}
