//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassIssueSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PassIssueHed
    {
        [Key]
        public string PassNo { get; set; }

        [Required]
        [Display(Name = "Pass Request No")]
        public string PassReqNo { get; set; }

        [Display(Name = "Issued Date")]
        public System.DateTime IssueDate { get; set; }

        [Required]
        [Display(Name = "Valid From")]
        public System.DateTime ValidFrom { get; set; }

        [Required]
        [Display(Name = "Valid To")]
        public System.DateTime ValidTo { get; set; }

        [Display(Name = "VIP")]
        public decimal IsVIP { get; set; }


        public System.DateTime AddDate { get; set; }
        public string AddUser { get; set; }
    
        public virtual PassRequestHed PassRequestHed { get; set; }
    }
}
