//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassIssueSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PassRequestDet
    {
        [Key]
        public string PassReqNo { get; set; }
        public string PersonNIC { get; set; }
        public string PersonName { get; set; }
        public string PassCode { get; set; }
        public decimal PassFee { get; set; }
    
        public virtual PassRequestHed PassRequestHed { get; set; }
        public virtual PassType PassType { get; set; }
    }
}
