//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassIssueSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PassType
    {
        public PassType()
        {
            this.PassRequestDets = new HashSet<PassRequestDet>();
        }

        [Key]
        public string PassCode { get; set; }
        public string Description { get; set; }
        public decimal PassFee { get; set; }
        public decimal Status { get; set; }
        public System.DateTime AddDate { get; set; }
        public string AddUser { get; set; }
    
        public virtual ICollection<PassRequestDet> PassRequestDets { get; set; }
    }
}
