//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassIssueSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class VehicleType
    {
        public VehicleType()
        {
            this.PassReqVehicles = new HashSet<PassReqVehicle>();
        }

        [Key]
        [Display(Name = "Vehicle Code")]
        [StringLength(8)]
        public string VehicleCode { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Fee")]
        [Required]
        public decimal VehicleFee { get; set; }

        [Display(Name = "Status")]
        public decimal Status { get; set; }

        public System.DateTime AddDate { get; set; }
        public string AddUser { get; set; }
    
        public virtual ICollection<PassReqVehicle> PassReqVehicles { get; set; }
    }
}
